pipeline {
    agent { node { label 'AGENT-1' } }
    options {
        ansiColor('xterm')
    }

    stages {
        stage('Init') {
            steps {
                
                sh '''
                cd 01-vpc
                ls -ltr
                pwd
                terraform init -reconfigure
                '''
            }
        }
        stage('Plan') {
            steps {
                sh '''
                cd 01-vpc
                ls -ltr
                pwd
                terraform plan
                '''
            }
        }
        stage('Approve') {
            steps {
                input "Shall I apply ?"
            }
        }
        stage('Apply') {
            steps {
                sh ' terraform apply -auto-approve '
            }
        }
    }
    post { 
            always { 
                echo 'I will always run whether job is success or not'
            }
            success {
                echo 'i will run only if the job is success'
            }
            failure {
                echo 'I will run only when the job is failure'
            }
        }
}